name: Perks
authors: [N3wton, wman2]
main: me.wisbycraft.perks.Perks
version: 1.4
website: www.wisbycraft.com
description: A plugin containing all the Donator perks for WisbyCraft
softdepend: [Spout]

commands:
   perks:
      description: Lists all player perks.
      usage: /<command>
      
   fly:
      description: Turns fly mode on.
      usage: /<command>
     
   mc:
      description: Turns magic carpet mode on.
      usage: /<command>
      
   gmtoggle:
      description: Toggles a players gamemode
      usage: /<command>

   gm:
      description: Lets you see a players gamemode
      usage: /<command> [player]
   
   creative:
      description: puts you into creative mode
      usage: /<command>

   survival:
      description: puts you into survival mode
      usage: /<command>
      
   tpr:
      description: Request to be teleported to player
      usage: /<command> <player>
      
   tphr:
      description: Request to teleport a player to you
      usage: /<command> <player>
      
   tpa:
      description: Accept a players teleport request
      usage: /<command> [player]
      
   tpd:
      description: Accept a players teleport request
      usage: /<command> [player]
     
   death:
      description: Teleport to your last death point
      usage: /<command>
   capes:
      description: cape overide commands
      usage: /<command> <update/remove> [player]
   promote:
      description: promote command
      usage: /<command> <player> [ladder]