name: Perks
authors: [N3wton, wman2]
main: me.wisbycraft.perks.Perks
version: 1.00
website: wisbycraft.com
description: A plugin containing all the Donator perks for our server
depend: [Spout]

commands:
   fly:
      description: Turns fly mode on.
      usage: /<command>
      
   land:
      description: Turns fly mode off.
      usage: /<command>
      
   flytoggle:
      description: Toggles fly mode.
      usage: /<command>

