name: Perks
authors: [N3wton, wman2]
main: uk.codingbadgers.perks.Perks
version: 1.95
website: www.mcbadgercraft.com
description: A plugin containing all the standard commands for McBadgerCraft
softdepend: [Spout, MobArena, dynmap, Multiverse-Core, Vault]
depend: [bDatabaseManager]

commands:
   perks:
      description: Lists all player perks.
      usage: /<command>
      
   fly:
      description: Turns fly mode on.
      usage: /<command>
        
   land:
      description: forces your fly mode off
      usage: /<command>
      
   gmtoggle:
      description: Toggles a players gamemode
      usage: /<command>

   gm:
      description: Base gamemode command
      usage: /<command> <player> [mode]
      
   creative:
      description: puts you into creative mode
      usage: /<command>

   survival:
      description: puts you into survival mode
      usage: /<command>
   
   adventure:
      description: puts you into adventure mode
      usage: /<command>
   
   tpr:
      description: Request to be teleported to player
      usage: /<command> <player>
      
   tphr:
      description: Request to teleport a player to you
      usage: /<command> <player>
      
   put:
      description: Put a player where you are looking
      usage: /<command> <player>
      
   tpa:
      description: Accept a players teleport request
      usage: /<command> [player]
      
   tpd:
      description: Accept a players teleport request
      usage: /<command> [player]
     
   death:
      description: Teleport to your last death point
      usage: /<command>
       
   home:
      description: Teleport you to your current worlds home
      usage: /<command> [world]
      
   sethome:
      description: Sets your home in the current world
      usage: /<command>
      
   build:
      description: Teleport you to your current build location
      usage: /<command>
      
   setbuild:
      description: Sets your build location
      usage: /<command>
  
   promote:
      description: promote command
      usage: /<command> <player> [ladder]
      
   demote:
      description: demote command
      usage: /<command> <player> [ladder]
      
   vanish:
      description: lets you vanish
      usage: /<command>
      
   list:
      description: lists all online players
      aliases: [who,players]
      usage: /<command>
      
   item:
      description: gives yourself items 
      usage: /<command> [-do] <item> [ammount] [player]
      aliases: [i]
   
   afk:
      description: teleports you to your afk spot
      usage: /<command>
      
   tphere:
      description: teleports another player here
      aliases: [s, bring]
      usage: /<command> <target>
   
   tp:
      description: teleports you to another player
      usage: /<command> <target>
   
   kit:
      description: kit commands
      usage: /<command> [target]  
      
   clear:
      description: Clears a players inventory
      usage: /<command> [-sa] [player]
      
   time:
      description: changes the time
      usage: /<command> [-ls] <time> [world]
      
   playertime:
      description: changes the time for a specific player
      usage: /<command> [-l] <time> [player]
        
   weather:
      description: changes the weather
      usage: /<command> [-s] <state> [duration] [world]
      
   perksadmin:
      description: admin commands
      aliases: [padmin]
      usage: /<command> <argument>
      
   debug:
      description: debug stuff
      usage: /<command> <clock/info>
      
   lookup:
      description: lookup a player
      usage: /<command> <target>
      
   ping:
      description: pong
      usage: /<command>
      
   spawn:
      description: teleports you to spawn
      usage: /<command>
      
   setspawn:
      description: sets the spawn
      usage: /<command>
      
   spectate:
      description: spectate a player
      usage: /<command> <target>
      
   slap:
      description: slaps a player
      usage: /<command> [-hvs] <target>
      
   rocket:
      description: rockets a player
      usage: /<command> [-hs] <target>
      
   thor:
      description: grants the use of thors hammer
      usage: /<command>
      
   shock:
      description: shocks a player
      usage: /<command> [-s] <target>
      
   restart:
      description: restarts the server taking an optional delay time
      usage: /<command> [time]
      
   hide:
      description: hide's yourself from livemap
      usage: /<command>
      
   show:
      description: show's yourself on livemap
      usage: /<command>
 
   setspawn:
      description: sets the spawn for the world you are in
      usage: /<command>
      
   plugins:
      description: lists all plugins that arn't blacklisted
      usage: /<command>
      aliases: [pl, pldebug]
      
   forcestop:
      description: force stop the server without timeout
      usage: /<command>
      
   fakeop:
      description: Fake op a player
      usage: /<command> <player> 
      
   speak:
      description: Speak as another player
      usage: /<command> <player> <message>
      
   rename:
      description: rename a player
      usage: /<command> <player> <name>
      
   giveall:
      description: give all the players on the server a item
      usage: /<command> <item>[:meta] [amount]
      
   stopstop:
      description: cancels the stop countdown
      usage: /<command>
      
   groupset:
      description: sets the group of a user
      usage: /<command> <player> <group>
      
   sendCommand:
      description: send a command as another player
      usage: /<command> <player> <command> [args]