name: Perks
authors: [N3wton, wman2]
main: me.wisbycraft.perks.Perks
version: 1.00
website: www.wisbycraft.com
description: A plugin containing all the Donator perks for our server
depend: [Spout]

commands:
   fly:
      description: Turns fly mode on.
      usage: /<command>
      
   land:
      description: Turns fly mode off.
      usage: /<command>
      
   flytoggle:
      description: Toggles fly mode.
      usage: /<command>
      
   gmtoggle:
      description: Toggles a players gamemode
      usage: /<command>

   gm:
      description: Lets you see a players gamemode
      usage: /<command>
   
   creative:
      description: puts you into creative mode
      usage: /<command>

   survival:
      description: puts you into survival mode
      usage: /<command>
   tpr:
      description: Request to be teleported to player
      usage: /<command> <player>
      
   tpa:
      description: Accept a players teleport request
      usage: /<command> [player]
      
   tpd:
      description: Accept a players teleport request
      usage: /<command> [player]